In [2]:
import tensorflow as tf
print(tf.__version__)

2.0.0


# The Sequential model API

 #### [1. Building a Sequential model](#coding_tutorial_1)
 #### [2. Convolutional and pooling layers](#coding_tutorial_2)
 #### [3. The Compile method](#coding_tutorial_3)
 #### [4. The Fit Method](#coding_tutorial_4)
 #### [5. The Evaluate and Predict Methods](#coding_tutorial_5)

***
<a id="coding_tutorial_1"></a>
## Building a Sequential model

In [5]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Softmax

### Building a feedforward neural network model

In [18]:
model = Sequential([
    Flatten(input_shape=(28,28)),
    Dense(16, activation='relu', name='layer_1'),
    Dense(16, activation='relu'),
    Dense(10, activation='softmax')
])

In [19]:
model.weights

[<tf.Variable 'layer_1/kernel:0' shape=(784, 16) dtype=float32, numpy=
 array([[-0.04307619, -0.07812451,  0.06170815, ..., -0.05177376,
          0.0320112 , -0.03688396],
        [ 0.06937711,  0.04792733, -0.0731418 , ..., -0.04171295,
         -0.07820623, -0.07686754],
        [ 0.04358263,  0.04252531,  0.01080967, ..., -0.04598842,
         -0.07807469,  0.01332193],
        ...,
        [ 0.06506421, -0.07316777, -0.01552261, ..., -0.0214532 ,
          0.02854934, -0.07704503],
        [ 0.00860772, -0.00516685,  0.05999406, ...,  0.03630607,
         -0.02547561,  0.07347621],
        [-0.00263854, -0.03621844,  0.02067712, ..., -0.06988331,
          0.02445595,  0.06008248]], dtype=float32)>,
 <tf.Variable 'layer_1/bias:0' shape=(16,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=float32)>,
 <tf.Variable 'dense_12/kernel:0' shape=(16, 16) dtype=float32, numpy=
 array([[ 0.27290657,  0.25812778, -0.17946652, -0.11

In [20]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_3 (Flatten)          (None, 784)               0         
_________________________________________________________________
layer_1 (Dense)              (None, 16)                12560     
_________________________________________________________________
dense_12 (Dense)             (None, 16)                272       
_________________________________________________________________
dense_13 (Dense)             (None, 10)                170       
Total params: 13,002
Trainable params: 13,002
Non-trainable params: 0
_________________________________________________________________


***
<a id="coding_tutorial_2"></a>
## Convolutional and pooling layers

In [22]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten

In [32]:
model = Sequential([
    Conv2D(16, (3, 3), padding='SAME', strides=2, activation='relu', input_shape=(28, 28, 1), data_format='channels_last'),
    MaxPooling2D((3, 3)),
    Flatten(),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])

In [33]:
model.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_4 (Conv2D)            (None, 14, 14, 16)        160       
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 4, 4, 16)          0         
_________________________________________________________________
flatten_8 (Flatten)          (None, 256)               0         
_________________________________________________________________
dense_22 (Dense)             (None, 64)                16448     
_________________________________________________________________
dense_23 (Dense)             (None, 10)                650       
Total params: 17,258
Trainable params: 17,258
Non-trainable params: 0
_________________________________________________________________
