In [1]:
import tensorflow as tf
print(tf.__version__)

2.0.0


# The Sequential model API

 #### [1. Building a Sequential model](#coding_tutorial_1)
 #### [2. Convolutional and pooling layers](#coding_tutorial_2)
 #### [3. The Compile method](#coding_tutorial_3)
 #### [4. The Fit Method](#coding_tutorial_4)
 #### [5. The Evaluate and Predict Methods](#coding_tutorial_5)

***
<a id="coding_tutorial_1"></a>
## Building a Sequential model

In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Softmax

### Building a feedforward neural network model

In [3]:
model = Sequential([
    Flatten(input_shape=(28,28)),
    Dense(16, activation='relu', name='layer_1'),
    Dense(16, activation='relu'),
    Dense(10, activation='softmax')
])

In [4]:
model.weights

[<tf.Variable 'layer_1/kernel:0' shape=(784, 16) dtype=float32, numpy=
 array([[-0.02384437, -0.03149036, -0.08060737, ..., -0.05897936,
         -0.01425504, -0.04586843],
        [ 0.07172589, -0.02048689, -0.03843299, ...,  0.01989585,
         -0.00787532, -0.08057859],
        [ 0.08591872,  0.05930276, -0.0399745 , ...,  0.03449342,
         -0.01426693, -0.02716102],
        ...,
        [-0.02583354,  0.01893473, -0.0302849 , ...,  0.05456436,
          0.01729999,  0.04234985],
        [ 0.05221233,  0.04202463,  0.02441663, ..., -0.01080686,
         -0.0442236 , -0.07868712],
        [-0.07322951,  0.00493149,  0.08495279, ..., -0.08381911,
          0.01499835,  0.01317739]], dtype=float32)>,
 <tf.Variable 'layer_1/bias:0' shape=(16,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=float32)>,
 <tf.Variable 'dense/kernel:0' shape=(16, 16) dtype=float32, numpy=
 array([[-0.11266518,  0.13887903,  0.03747395, -0.14373

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
layer_1 (Dense)              (None, 16)                12560     
_________________________________________________________________
dense (Dense)                (None, 16)                272       
_________________________________________________________________
dense_1 (Dense)              (None, 10)                170       
Total params: 13,002
Trainable params: 13,002
Non-trainable params: 0
_________________________________________________________________


***
<a id="coding_tutorial_2"></a>
## Convolutional and pooling layers

In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten

In [7]:
model = Sequential([
    Conv2D(16, (3, 3), padding='SAME', strides=2, activation='relu', input_shape=(28, 28, 1), data_format='channels_last'),
    MaxPooling2D((3, 3)),
    Flatten(),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])

In [8]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 14, 14, 16)        160       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 4, 4, 16)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 256)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 64)                16448     
_________________________________________________________________
dense_3 (Dense)              (None, 10)                650       
Total params: 17,258
Trainable params: 17,258
Non-trainable params: 0
_________________________________________________________________


***
<a id="coding_tutorial_3"></a>
## The compile method

#### Compile the model

In [19]:
# Define the model optimizer, loss function and metrics
opt = tf.keras.optimizers.Adam(learning_rate=0.005)
acc = tf.keras.metrics.SparseCategoricalAccuracy()
mae = tf.keras.metrics.MeanAbsoluteError()

model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=[acc, mae])

In [20]:
# Print the resulting model attributes

print(model.optimizer)
print(model.loss)
print(model.metrics)
print(model.optimizer.lr)

categorical_crossentropy
[<tensorflow.python.keras.metrics.SparseCategoricalAccuracy object at 0x0000016C356E5FC8>, <tensorflow.python.keras.metrics.MeanAbsoluteError object at 0x0000016C356C4288>]
<tf.Variable 'learning_rate:0' shape=() dtype=float32, numpy=0.005>
